nvidia_a100:
  driver_version: "525.60.13"
  cuda_version: "11.8"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.14"
  frameworks:
    tensorflow: "2.10.0"
    pytorch: "2.0.0"
    qiskit: "latest"
    cirq: "latest"
    jax: "latest"
    onnxruntime: "latest"
  expected_performance:
    pytorch_matmul_ms: 0.8  # expected time in ms for a 1000x1000 matmul
    tf_resnet_inference_s: 0.02  # expected inference time on a small batch
    jax_matmul_ms: 0.7  # matrix multiplication for JAX
    onnx_inference_s: 0.015  # ONNX Runtime inference time
    note: "These are approximate values for comparison."

nvidia_rtx_3090:
  driver_version: "525.60.13"
  cuda_version: "11.7"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.12"
  frameworks:
    tensorflow: "2.9.0"
    pytorch: "1.13.0"
    qiskit: "latest"
    cirq: "latest"
    jax: "0.3.23"  # specific compatible version
    onnxruntime: "1.13.1"
  expected_performance:
    pytorch_matmul_ms: 1.0
    tf_resnet_inference_s: 0.03
    jax_matmul_ms: 0.9
    onnx_inference_s: 0.02
    note: "Approximate metrics for comparison."

unknown_gpu:
  driver_version: "525"
  cuda_version: "11.8"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.14"
  frameworks:
    tensorflow: "2.10.0"
    pytorch: "2.0.0"
    qiskit: "latest"
    cirq: "latest"
    jax: "latest"
    onnxruntime: "latest"
  # No expected_performance since unknown GPU

fallback:
  driver_version: "525"
  cuda_version: "11.8"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.14"
  frameworks:
    tensorflow: "2.10.0"
    pytorch: "2.0.0"
    qiskit: "latest"
    cirq: "latest"
    jax: "latest"
    onnxruntime: "latest"

# Cloud-Specific Configurations
aws_gpu:
  note: "AWS DL AMI often includes pre-installed drivers and frameworks."
  driver_version: "525"
  cuda_version: "11.8"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.14"
  frameworks:
    tensorflow: "2.10.0"
    pytorch: "2.0.0"
    jax: "latest"
    onnxruntime: "latest"

azure_gpu:
  note: "Azure NC/ND VMs support NVIDIA GPUs. Drivers might be pre-installed."
  driver_version: "525"
  cuda_version: "11.7"
  libraries:
    - name: cuDNN
      version: "8.3"
    - name: NCCL
      version: "2.12"
  frameworks:
    tensorflow: "2.9.0"
    pytorch: "1.13.0"
    jax: "0.3.23"
    onnxruntime: "1.12.0"

gcp_gpu:
  note: "GCP supports NVIDIA GPUs with custom driver installation."
  driver_version: "525"
  cuda_version: "11.8"
  libraries:
    - name: cuDNN
      version: "8.4"
    - name: NCCL
      version: "2.14"
  frameworks:
    tensorflow: "2.10.0"
    pytorch: "2.0.0"
    jax: "latest"
    onnxruntime: "latest"
